### ISSUE TITLE
Change underlying protocol on UDP

### ISSUE THREAD

**Issue by tsuzu** [cs3238-tsuzu/go-easyp2p#1]
[utp](github.com/anacrolix/utp), a library which is used by go-easyp2p is deprecated.(anacrolix/utp#26)
Therefore, we should use another library.

There are some candidates
- [quic-go](https://github.com/lucas-clemente/quic-go)
- [go-libutp](https://github.com/anacrolix/go-libutp)

However, all of these have problems.
## quic-go
- QUIC, which is a protocol used by quic-go is experimental.
- The architecture of QUIC is stream-multiplexing, so if I adopt it, APIs of go-easyp2p will have to be changed largely.

## go-libutp
- go-libutp depends on libutp, which is written in C/C++, so it will get more difficult to cross-compile programs using go-easyp2p.

I considered whether kcp-go can be used, but it doesn't implement control messages such as SYN/FIN/RST, so I think it's very difficult to adopt it.

If you know other libraries, please tell me them.

**Comment by tsuzu** [comment]
FIx in 66b9797

**Comment by jannson** [comment]
You can use "kcp-go" + "smux" .

**Comment by tsuzu** [comment]
Yes!
I like "kcp-go" and "smux" very much, (I use "smux" in [cs3238-tsuzu/ftrans](//github.com/cs3238-tsuzu/ftrans).) but I used QUIC because it is being standardized.

**Comment by anacrolix** [comment]
Has anacrolix/utp worked all right for you so far?

**Comment by tsuzu** [comment]
@anacrolix Yes. It worked perfectly. Thank you so much!
